apiVersion: v1
kind: ReplicationController
metadata:
  name: onlinestore-rc
spec:
  replicas: 2
  selector:
    app: onlinestore
    version: 2.6.1 

  template:
    metadata:
      name: nginx
      labels:
        app: onlinestore
        version: 2.6.1
        
    spec:
      containers:
        - name: myonlinestore-container
          image: maha4iac/mahaonlinestore:1
          ports:
            - containerPort: 8080

