apiVersion: v1
kind: Service
metadata:
  name: mynginx-svc
  labels:
    app: onlinestore
    version: 2.6.2
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30001
    protocol: TCP
  selector:
    app: onlinestore
    version: 2.6.2
